"use client";

import { useState } from "react";
import { checkStockIssue, deleteStockIssueItem, postStockIssue, saveStockIssueDraft, saveStockIssueItem } from "@/app/actions";
import { PickedProduct, ProductPicker } from "@/components/product-picker";

type Group = { id: string; name: string };
type Work = { id: string; code: number; name: string };
type Account = { id: string; code: string; name: string };
type Item = { id: string; productId: string; product: { number: number; name: string; unit: string; requiresExpiry: boolean; currentUnitCost: string; balance: string }; quantity: string; unitCost: string; total: string };
type Draft = { id: string; number: number; date: string; workId: string | null; debitAccountId: string | null; items: Item[] };

export function StockIssueManager({ initialDraft, groups, works, accounts, today }: { initialDraft: Draft | null; groups: Group[]; works: Work[]; accounts: Account[]; today: string }) {
  const [draft, setDraft] = useState(initialDraft), [date, setDate] = useState(initialDraft?.date || today), [workId, setWorkId] = useState(initialDraft?.workId || ""), [debitAccountId, setDebitAccountId] = useState(initialDraft?.debitAccountId || ""), [product, setProduct] = useState<PickedProduct | null>(null), [quantity, setQuantity] = useState(""), [unitCost, setUnitCost] = useState(""), [editing, setEditing] = useState<Item | null>(null), [errors, setErrors] = useState<Record<string, string>>({}), [notice, setNotice] = useState(""), [error, setError] = useState("");
  const total = (draft?.items || []).reduce((sum, item) => sum + Number(item.total), 0);
  async function persistHeader() { const form = new FormData(); if (draft) form.set("id", draft.id); form.set("date", date); form.set("workId", workId); form.set("debitAccountId", debitAccountId); const saved = await saveStockIssueDraft(form); if (!draft) setDraft({ id: saved.id, number: saved.number, date, workId: workId || null, debitAccountId: debitAccountId || null, items: [] }); else setDraft({ ...draft, date, workId: workId || null, debitAccountId: debitAccountId || null }); return saved.id; }
  function resetItem() { setProduct(null); setQuantity(""); setUnitCost(""); setEditing(null); }
  async function saveItem(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!product) return setError("Selecione um produto."); try { setError(""); const issueId = draft?.id || await persistHeader(); const form = new FormData(); form.set("id", editing?.id || ""); form.set("issueId", issueId); form.set("productId", product.id); form.set("quantity", quantity); form.set("unitCost", unitCost); await saveStockIssueItem(form); const item: Item = { id: editing?.id || `pending-${product.id}`, productId: product.id, product: { number: product.number, name: product.name, unit: product.unit, requiresExpiry: product.requiresExpiry, currentUnitCost: product.currentUnitCost, balance: product.balance }, quantity, unitCost, total: (Number(quantity) * Number(unitCost)).toFixed(2) };
      setDraft((current) => current ? { ...current, items: editing ? current.items.map((row) => row.id === editing.id ? item : row) : [...current.items, item] } : current); resetItem(); setNotice("Item incluído na lista temporária."); setErrors({});
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar o item."); } }
  async function removeItem(item: Item) { if (!draft || item.id.startsWith("pending-")) return; try { const form = new FormData(); form.set("id", item.id); form.set("issueId", draft.id); await deleteStockIssueItem(form); setDraft({ ...draft, items: draft.items.filter((row) => row.id !== item.id) }); setErrors({}); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível excluir o item."); } }
  function editItem(item: Item) { setEditing(item); setProduct({ id: item.productId, number: item.product.number, name: item.product.name, unit: item.product.unit, balance: item.product.balance, requiresExpiry: item.product.requiresExpiry, currentUnitCost: item.product.currentUnitCost }); setQuantity(item.quantity); setUnitCost(item.unitCost); setNotice(""); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function check() { if (!draft) return setError("Inclua ao menos um item antes de conferir o estoque."); try { setError(""); await persistHeader(); const found = await checkStockIssue(draft.id); setErrors(found); setNotice(Object.keys(found).length ? "Há itens com saldo insuficiente destacados em vermelho." : "Estoque conferido. A lista pode ser efetivada."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível conferir o estoque."); } }
  async function post() { if (!draft) return; try { setError(""); await persistHeader(); const found = await checkStockIssue(draft.id); setErrors(found); if (Object.keys(found).length) return setNotice("Corrija os itens destacados antes de efetivar."); await postStockIssue(draft.id); setNotice(`Baixa nº ${draft.number} efetivada com sucesso.`); setDraft(null); setErrors({}); resetItem(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível efetivar a baixa."); } }
  return <>
    <section className="card"><div className="list-head"><div><h2>{draft ? `Lista de baixa nº ${draft.number}` : "Nova lista de baixa"}</h2><p className="muted">A lista fica salva como rascunho e pode ser retomada depois.</p></div>{draft && <span className="badge">Rascunho</span>}</div><div className="form-grid"><label className="field">Data única da saída<input type="date" value={date} onChange={(event) => setDate(event.target.value)} onBlur={() => { if (draft) void persistHeader(); }} required /></label><label className="field">Obra<select value={workId} onChange={(event) => { setWorkId(event.target.value); setDebitAccountId(""); }} onBlur={() => { if (draft) void persistHeader(); }}><option value="">Sem vínculo com obra</option>{works.map((work) => <option key={work.id} value={work.id}>{work.code} — {work.name}</option>)}</select></label>{!workId && <label className="field">Conta de despesa<select value={debitAccountId} onChange={(event) => setDebitAccountId(event.target.value)} onBlur={() => { if (draft) void persistHeader(); }}><option value="">Selecione para efetivar</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</select></label>}{workId && <p className="form-hint">Com obra, a baixa debita automaticamente a conta 4.3 — Materiais.</p>}</div></section>
    <section className={`card mt${editing ? " editing-card" : ""}`}><h2>{editing ? `Editando item: ${editing.product.name}` : "Adicionar produto à lista"}</h2><form className="form-grid" onSubmit={saveItem}><ProductPicker value={product} onChange={(selected) => { setProduct(selected); setUnitCost(selected.currentUnitCost); }} groups={groups} label="Produto" />{product && <div className="field"><span>Saldo disponível</span><strong>{product.balance} {product.unit}</strong></div>}<label className="field">Quantidade<input type="number" min="1" step="1" value={quantity} onChange={(event) => setQuantity(event.target.value)} required /></label><label className="field">Valor unitário<input type="number" min="0" step="0.0001" value={unitCost} onChange={(event) => setUnitCost(event.target.value)} required /></label><div className="form-actions">{editing && <button className="btn secondary" type="button" onClick={resetItem}>Cancelar edição</button>}<button className="btn">{editing ? "Salvar alteração" : "Adicionar à lista"}</button></div></form></section>
    <section className="card mt"><div className="list-head"><h2>Itens da lista</h2><span className="muted">{draft?.items.length || 0} produto(s) · Total {total.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</span></div>{!draft?.items.length ? <p className="muted">Nenhum item foi adicionado.</p> : <div className="table-wrap"><table><thead><tr><th>Código</th><th>Produto</th><th>Saldo</th><th>Data da saída</th><th>Quantidade</th><th>Valor unitário</th><th>Total</th><th></th></tr></thead><tbody>{draft.items.map((item) => <tr key={item.id} className={errors[item.id] ? "row-error" : ""} onDoubleClick={() => editItem(item)}><td>{item.product.number}</td><td>{item.product.name}{errors[item.id] && <small className="error-text">{errors[item.id]}</small>}</td><td>{item.product.balance} {item.product.unit}</td><td>{new Date(`${date}T12:00:00`).toLocaleDateString("pt-BR")}</td><td>{item.quantity}</td><td>{Number(item.unitCost).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</td><td>{Number(item.total).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</td><td><button className="btn secondary" type="button" onClick={() => editItem(item)}>Editar</button> <button className="link-button" type="button" onClick={() => void removeItem(item)}>Excluir</button></td></tr>)}</tbody></table></div>}<div className="form-actions mt"><button className="btn secondary" type="button" onClick={() => void check()} disabled={!draft?.items.length}>Checar estoque</button><button className="btn" type="button" onClick={() => void post()} disabled={!draft?.items.length}>Efetivar todos os lançamentos</button></div>{error && <p className="form-error">{error}</p>}{notice && <p className="form-success">{notice}</p>}</section>
  </>;
}
